# Week2

# using manual

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_excel('multivariate.xlsx')

In [3]:
df

Subject     Y  X1  X2
0        1  -3.7   3   8
1        2   3.5   4   5
2        3   2.5   5   7
3        4  11.5   6   3
4        5   5.7   2   1

In [4]:
X1=np.array(df['X1'])
X1

array([3, 4, 5, 6, 2], dtype=int64)

In [5]:
X2=np.array(df['X2'])
X2

array([8, 5, 7, 3, 1], dtype=int64)

In [6]:
Y=np.array(df['Y'])
Y

array([-3.7,  3.5,  2.5, 11.5,  5.7])

In [7]:
X1X2=X1*X2
X1X2

array([24, 20, 35, 18,  2], dtype=int64)

In [8]:
X1X1=X1*X1
X1X1

array([ 9, 16, 25, 36,  4], dtype=int64)

In [9]:
X2X2=X2*X2
X2X2

array([64, 25, 49,  9,  1], dtype=int64)

In [10]:
X1Y=X1*Y
X1Y

array([-11.1,  14. ,  12.5,  69. ,  11.4])

In [11]:
X2Y=X2*Y
X2Y

array([-29.6,  17.5,  17.5,  34.5,   5.7])

In [12]:
sum_x12=np.sum(X1X1)-((np.sum(X1)*np.sum(X1))/len(X1))
sum_x12

10.0

In [13]:
sum_x22=np.sum(X2X2)-((np.sum(X2)*np.sum(X2))/len(X2))
sum_x22

32.8

In [14]:
sum_x1y=np.sum(X1Y)-((np.sum(X1)*np.sum(Y))/len(X1))
sum_x1y

17.80000000000001

In [15]:
sum_x2y=np.sum(X2Y)-((np.sum(X2)*np.sum(Y))/len(X2))
sum_x2y

-47.99999999999999

In [16]:
sum_x1x2=np.sum(X1X2)-((np.sum(X1)*np.sum(X2))/len(X2))
sum_x1x2

3.0

In [17]:
b1=(((sum_x22)*(sum_x1y))-((sum_x1x2)*(sum_x2y)))/(((sum_x12)*(sum_x22))-((sum_x1x2)*(sum_x1x2)))
b1

2.2816300940438885

In [18]:
b2=(((sum_x12)*(sum_x2y))-((sum_x1x2)*(sum_x1y)))/(((sum_x12)*(sum_x22))-((sum_x1x2)*(sum_x1x2)))
b2

-1.6721003134796237

In [19]:
a=np.mean(Y)-(b1*(np.mean(X1)))-(b2*(np.mean(X2)))
a

2.7995611285266406

### Final equation

In [20]:
y=a+(b1*X1)+(b2*X2)
y

array([-3.7323511 ,  3.56557994,  2.5030094 , 11.47304075,  5.690721  ])

In [21]:
# Manual Method Prediction
x1=3
x2=2
Y=a+(b1*x1)+(b2*x2)
Y

6.300250783699058

## Manual and Random Integer

In [22]:
X1=np.random.randint(2,high=20,size=10)
X2=np.random.randint(2,high=20,size=10)
Y=np.random.randint(2,high=20,size=10)

In [23]:
X1

array([14, 13, 13, 16,  3, 18, 14, 10,  6,  4])

In [24]:
X2

array([ 3,  7,  9, 15, 13,  4, 12,  2, 14,  4])

In [25]:
Y

array([ 7, 16,  8, 10, 14, 14,  5,  2, 14, 12])

In [26]:
X1X2=X1*X2
X1X2

array([ 42,  91, 117, 240,  39,  72, 168,  20,  84,  16])

In [27]:
X1X1=X1*X1
X1X1

array([196, 169, 169, 256,   9, 324, 196, 100,  36,  16])

In [28]:
X2X2=X2*X2
X2X2

array([  9,  49,  81, 225, 169,  16, 144,   4, 196,  16])

In [29]:
X1Y=X1*Y
X1Y

array([ 98, 208, 104, 160,  42, 252,  70,  20,  84,  48])

In [30]:
X2Y=X2*Y
X2Y

array([ 21, 112,  72, 150, 182,  56,  60,   4, 196,  48])

In [31]:
sum_x12=np.sum(X1X1)-((np.sum(X1)*np.sum(X1))/len(X1))
sum_x12

238.9000000000001

In [32]:
sum_x22=np.sum(X2X2)-((np.sum(X2)*np.sum(X2))/len(X2))
sum_x22

220.10000000000002

In [33]:
sum_x1y=np.sum(X1Y)-((np.sum(X1)*np.sum(Y))/len(X1))
sum_x1y

-46.200000000000045

In [34]:
sum_x2y=np.sum(X2Y)-((np.sum(X2)*np.sum(Y))/len(X2))
sum_x2y

54.39999999999998

In [35]:
sum_x1x2=np.sum(X1X2)-((np.sum(X1)*np.sum(X2))/len(X2))
sum_x1x2

-32.299999999999955

In [36]:
b1=(((sum_x22)*(sum_x1y))-((sum_x1x2)*(sum_x2y)))/(((sum_x12)*(sum_x22))-((sum_x1x2)*(sum_x1x2)))
b1

-0.1632077704865869

In [37]:
b2=(((sum_x12)*(sum_x2y))-((sum_x1x2)*(sum_x1y)))/(((sum_x12)*(sum_x22))-((sum_x1x2)*(sum_x1x2)))
b2

0.2232094003329542

In [38]:
a=np.mean(Y)-(b1*(np.mean(X1)))-(b2*(np.mean(X2)))
a

10.158968229637594

### Final equation

In [39]:
y=a+(b1*X1)+(b2*X2)
y

array([ 8.54368764,  9.59973302, 10.04615182, 10.89578491, 12.57106712,
        8.11406596, 10.55257225,  8.97330933, 12.30465321, 10.39897475])

In [40]:
# Manual Method Prediction
x1=3
x2=2
Y=a+(b1*x1)+(b2*x2)
Y

10.115763718843741

## Manual and Random Floating numbers

In [41]:
X1=[]
for i in range(1,6):
    x=(np.random.uniform(1,20))
    X1.append(x)
X1=np.array(X1)

X2=[]
for i in range(1,6):
    x=(np.random.uniform(1,20))
    X2.append(x)
X2=np.array(X2)

Y=[]
for i in range(1,6):
    x=(np.random.uniform(1,20))
    Y.append(x)
Y=np.array(Y)

In [42]:
X1

array([17.16631143,  1.48608989,  1.90200245,  2.82044542, 14.24086203])

In [43]:
X2

array([16.23273574,  8.2779344 ,  4.95842969, 15.83773619, 10.13277652])

In [44]:
Y

array([18.39326891, 16.99323715,  8.01481877, 16.66330108,  7.73763961])

In [46]:
X1X2=X1*X2
X1X2

array([278.65619713,  12.30175465,   9.43094541,  44.66947053,
       144.29947234])

In [47]:
X1X1=X1*X1
X1X1

array([294.68224823,   2.20846317,   3.61761332,   7.95491238,
       202.80215131])

In [48]:
X2X2=X2*X2
X2X2

array([263.50170959,  68.5241979 ,  24.58602498, 250.83388749,
       102.67315994])

In [49]:
X1Y=X1*Y
X1Y

array([315.74458238,  25.25347798,  15.24420493,  46.99793126,
       110.1906581 ])

In [50]:
X2Y=X2*Y
X2Y

array([298.57307359, 140.66890235,  39.74091534, 263.9089665 ,
        78.40377292])

In [51]:
sum_x12=np.sum(X1X1)-((np.sum(X1)*np.sum(X1))/len(X1))
sum_x12

228.27704219902574

In [52]:
sum_x22=np.sum(X2X2)-((np.sum(X2)*np.sum(X2))/len(X2))
sum_x22

95.4088524298379

In [53]:
sum_x1y=np.sum(X1Y)-((np.sum(X1)*np.sum(Y))/len(X1))
sum_x1y

3.344766575521362

In [54]:
sum_x2y=np.sum(X2Y)-((np.sum(X2)*np.sum(Y))/len(X2))
sum_x2y

69.50936489389574

In [55]:
sum_x1x2=np.sum(X1X2)-((np.sum(X1)*np.sum(X2))/len(X2))
sum_x1x2

72.27774897132792

In [56]:
b1=(((sum_x22)*(sum_x1y))-((sum_x1x2)*(sum_x2y)))/(((sum_x12)*(sum_x22))-((sum_x1x2)*(sum_x1x2)))
b1

-0.2841858006894331

In [57]:
b2=(((sum_x12)*(sum_x2y))-((sum_x1x2)*(sum_x1y)))/(((sum_x12)*(sum_x22))-((sum_x1x2)*(sum_x1x2)))
b2

0.9438293466904808

In [58]:
a=np.mean(Y)-(b1*(np.mean(X1)))-(b2*(np.mean(X2)))
a

5.233316652139507

### Final equation

In [59]:
y=a+(b1*X1)+(b2*X2)
y

array([15.67582706, 12.62394842,  9.37270602, 19.37990631, 10.74987771])

In [60]:
# Manual Method Prediction
x1=3
x2=2
Y=a+(b1*x1)+(b2*x2)
Y

6.268417943452169